### ISSUE TITLE
Upgrade DateInput to use ^4.0.0 of react-datepicker

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/lp-components#305]
As of `2.0.0`, there is no longer a moment dependency (important for bundle size considerations)

**Comment by dpikt** [comment]
So, we tried this out in #332. Turns out the library is a little too unreliable to make the switch at this moment. I think we should keep our eye on it and try again in a few releases, since it's a pretty widely used library and I have faith in the crowd to iron it out eventually.

In the meantime we could also investigate another solution (per #273) but a lot of those have a moment dependency too...

**Comment by chawes13** [comment]
React datepicker is on `4.2.1` now. We should investigate making the upgrade

https://www.npmjs.com/package/react-datepicker
