### ISSUE TITLE
Add `remove` button to default file input previews

### ISSUE THREAD

**Issue by dpikt** [LaunchPadLab/lp-components#347]
A little `x` that will set the value of the field back to an empty string (clear it).

**Comment by chawes13** [comment]
@nicoledow Are you still interested in tackling this issue?

**Comment by nicoledow** [comment]
@chawes13 Thanks for reminding me - I started this but never finished. But yes, still interested, and will wrap it up this week!

**Comment by chawes13** [comment]
Thanks! It might be helpful to look at how the remove button as added for some breaking change functionality that is pending in v6.

https://github.com/LaunchPadLab/lp-components/blob/7da7efea655a0716e5988eb676be68472f1d5106/src/forms/inputs/file-input/file-input.js#L237-L248

Since this is a breaking change anyways (no backwards compatibility), it _probably_ makes sense for you to branch off of `v6` and tweak that existing code to always show the button when a file exists?

**Comment by nicoledow** [comment]
@chawes13 just tagged you in [the PR!](https://github.com/LaunchPadLab/lp-components/pull/526)
